import type { AdminUser, CrmLead } from './types';

export const MOCK_ADMIN_USERS: AdminUser[] = [
  { id: 'admin-1', name: 'Priya Sharma', email: 'priya@viralbridge.io' },
  { id: 'admin-2', name: 'Rahul Mehta', email: 'rahul@viralbridge.io' },
  { id: 'admin-3', name: 'Ananya Patel', email: 'ananya@viralbridge.io' },
];

export const LEAD_TYPE_OPTIONS = [
  'Brand',
  'Creator',
  'Agency',
  'Enterprise Client',
  'Investor',
  'Partner',
  'Other',
] as const;

export const LEAD_SOURCE_OPTIONS = [
  'Website',
  'Referral',
  'Social Media',
  'Email Campaign',
  'Cold Call',
  'Manual Entry',
  'Advertisement',
] as const;

export const PRIORITY_OPTIONS = ['Low', 'Medium', 'High', 'Critical'] as const;

export const LEAD_STATUS_OPTIONS = [
  'New',
  'Contacted',
  'Qualified',
  'Proposal Sent',
  'Negotiation',
  'Won',
  'Lost',
  'Inactive',
] as const;

export const TAG_OPTIONS = [
  'Hot Lead',
  'VIP',
  'Follow Up',
  'Demo Scheduled',
  'Enterprise',
  'Startup',
  'International',
  'Referral Partner',
];

const now = new Date();
const daysAgo = (n: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  return d.toISOString();
};

const today = now.toISOString().slice(0, 10);

export const MOCK_LEADS: CrmLead[] = [
  {
    id: 'lead-1',
    firstName: 'Arjun',
    lastName: 'Kapoor',
    gender: 'Male',
    email: 'arjun@stylehub.in',
    phone: '+91 98765 43210',
    whatsapp: '+91 98765 43210',
    website: 'https://stylehub.in',
    company: 'StyleHub India',
    jobTitle: 'Marketing Director',
    industry: 'Fashion & Retail',
    companySize: '50-200',
    country: 'India',
    state: 'Maharashtra',
    city: 'Mumbai',
    leadType: 'Brand',
    leadSource: 'Website',
    priority: 'High',
    leadStatus: 'Qualified',
    assignedToId: 'admin-1',
    assignedToName: 'Priya Sharma',
    dealCurrency: 'INR',
    dealValue: 250000,
    nextFollowUpDate: today,
    nextFollowUpTime: '14:00',
    description: 'Interested in creator campaigns for festive season launch.',
    internalNotes: 'Decision maker. Budget approved for Q4.',
    tags: ['Hot Lead', 'Enterprise'],
    notes: [
      {
        id: 'note-1',
        content: 'Initial call went well. They want a proposal by Friday.',
        createdBy: 'Priya Sharma',
        createdAt: daysAgo(2),
      },
    ],
    followUps: [
      {
        id: 'fu-1',
        title: 'Send campaign proposal',
        date: today,
        time: '14:00',
        status: 'today',
        createdAt: daysAgo(3),
      },
    ],
    attachments: [
      { id: 'att-1', name: 'StyleHub_Brief.pdf', type: 'pdf', size: '1.2 MB', uploadedAt: daysAgo(2) },
    ],
    timeline: [
      { id: 'tl-1', type: 'lead_created', title: 'Lead Created', createdBy: 'Priya Sharma', createdAt: daysAgo(5) },
      { id: 'tl-2', type: 'status_changed', title: 'Status Changed to Qualified', description: 'New → Qualified', createdBy: 'Priya Sharma', createdAt: daysAgo(2) },
      { id: 'tl-3', type: 'note_added', title: 'Note Added', createdBy: 'Priya Sharma', createdAt: daysAgo(2) },
    ],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
  },
  {
    id: 'lead-2',
    firstName: 'Meera',
    lastName: 'Singh',
    gender: 'Female',
    email: 'meera.creates@gmail.com',
    phone: '+91 91234 56789',
    company: 'Meera Creates',
    jobTitle: 'Content Creator',
    industry: 'Lifestyle',
    leadType: 'Creator',
    leadSource: 'Social Media',
    priority: 'Medium',
    leadStatus: 'Contacted',
    assignedToId: 'admin-2',
    assignedToName: 'Rahul Mehta',
    dealCurrency: 'INR',
    dealValue: 50000,
    nextFollowUpDate: new Date(now.getTime() + 86400000 * 2).toISOString().slice(0, 10),
    nextFollowUpTime: '11:00',
    description: 'Beauty & lifestyle creator with 500K followers on Instagram.',
    tags: ['Follow Up'],
    notes: [],
    followUps: [
      {
        id: 'fu-2',
        title: 'Onboarding call',
        date: new Date(now.getTime() + 86400000 * 2).toISOString().slice(0, 10),
        time: '11:00',
        status: 'upcoming',
        createdAt: daysAgo(1),
      },
    ],
    attachments: [],
    timeline: [
      { id: 'tl-4', type: 'lead_created', title: 'Lead Created', createdBy: 'Rahul Mehta', createdAt: daysAgo(3) },
      { id: 'tl-5', type: 'email_sent', title: 'Welcome Email Sent', createdAt: daysAgo(2) },
    ],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },
  {
    id: 'lead-3',
    firstName: 'Vikram',
    lastName: 'Reddy',
    email: 'vikram@mediaforce.com',
    phone: '+91 99887 76655',
    company: 'MediaForce Agency',
    jobTitle: 'CEO',
    industry: 'Marketing Agency',
    companySize: '20-50',
    leadType: 'Agency',
    leadSource: 'Referral',
    priority: 'Critical',
    leadStatus: 'Negotiation',
    assignedToId: 'admin-1',
    assignedToName: 'Priya Sharma',
    dealCurrency: 'INR',
    dealValue: 500000,
    description: 'Agency partnership for white-label creator campaigns.',
    internalNotes: 'Competitive deal — need to close before month end.',
    tags: ['VIP', 'Referral Partner'],
    notes: [
      {
        id: 'note-2',
        content: 'Sent revised pricing. Awaiting counter-offer.',
        createdBy: 'Priya Sharma',
        createdAt: daysAgo(1),
      },
    ],
    followUps: [],
    attachments: [
      { id: 'att-2', name: 'Partnership_Agreement_Draft.pdf', type: 'pdf', size: '890 KB', uploadedAt: daysAgo(1) },
    ],
    timeline: [
      { id: 'tl-6', type: 'lead_created', title: 'Lead Created', createdAt: daysAgo(10) },
      { id: 'tl-7', type: 'meeting_added', title: 'Partnership Meeting Scheduled', createdAt: daysAgo(7) },
      { id: 'tl-8', type: 'status_changed', title: 'Status Changed to Negotiation', createdAt: daysAgo(3) },
    ],
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
  },
  {
    id: 'lead-4',
    firstName: 'Sarah',
    lastName: 'Chen',
    email: 'sarah.chen@globaltech.com',
    phone: '+1 415 555 0199',
    company: 'GlobalTech Inc.',
    jobTitle: 'VP Marketing',
    industry: 'Technology',
    companySize: '1000+',
    country: 'USA',
    city: 'San Francisco',
    leadType: 'Enterprise Client',
    leadSource: 'Email Campaign',
    priority: 'High',
    leadStatus: 'Proposal Sent',
    assignedToId: 'admin-3',
    assignedToName: 'Ananya Patel',
    dealCurrency: 'USD',
    dealValue: 75000,
    tags: ['Enterprise', 'International'],
    notes: [],
    followUps: [
      {
        id: 'fu-3',
        title: 'Follow up on proposal',
        date: new Date(now.getTime() - 86400000).toISOString().slice(0, 10),
        time: '16:00',
        status: 'overdue',
        createdAt: daysAgo(4),
      },
    ],
    attachments: [],
    timeline: [
      { id: 'tl-9', type: 'lead_created', title: 'Lead Created', createdAt: daysAgo(8) },
      { id: 'tl-10', type: 'status_changed', title: 'Status Changed to Proposal Sent', createdAt: daysAgo(4) },
    ],
    createdAt: daysAgo(8),
    updatedAt: daysAgo(4),
  },
  {
    id: 'lead-5',
    firstName: 'Rajesh',
    lastName: 'Kumar',
    email: 'rajesh@foodiebox.in',
    phone: '+91 87654 32109',
    company: 'FoodieBox',
    leadType: 'Brand',
    leadSource: 'Cold Call',
    priority: 'Low',
    leadStatus: 'Lost',
    assignedToId: 'admin-2',
    assignedToName: 'Rahul Mehta',
    dealCurrency: 'INR',
    dealValue: 80000,
    description: 'Budget constraints — may revisit next quarter.',
    tags: [],
    notes: [],
    followUps: [],
    attachments: [],
    timeline: [
      { id: 'tl-11', type: 'lead_created', title: 'Lead Created', createdAt: daysAgo(20) },
      { id: 'tl-12', type: 'status_changed', title: 'Status Changed to Lost', description: 'Budget not approved', createdAt: daysAgo(5) },
    ],
    createdAt: daysAgo(20),
    updatedAt: daysAgo(5),
  },
  {
    id: 'lead-6',
    firstName: 'Neha',
    lastName: 'Gupta',
    email: 'neha@venturecap.io',
    phone: '+91 99001 22334',
    company: 'Horizon Ventures',
    jobTitle: 'Partner',
    leadType: 'Investor',
    leadSource: 'Referral',
    priority: 'Medium',
    leadStatus: 'New',
    assignedToId: 'admin-3',
    assignedToName: 'Ananya Patel',
    dealCurrency: 'INR',
    tags: ['Startup'],
    notes: [],
    followUps: [],
    attachments: [],
    timeline: [
      { id: 'tl-13', type: 'lead_created', title: 'Lead Created', createdAt: daysAgo(1) },
    ],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'lead-7',
    firstName: 'Amit',
    lastName: 'Desai',
    email: 'amit@techstart.in',
    phone: '+91 98123 45678',
    company: 'TechStart Solutions',
    leadType: 'Brand',
    leadSource: 'Advertisement',
    priority: 'Medium',
    leadStatus: 'Won',
    assignedToId: 'admin-1',
    assignedToName: 'Priya Sharma',
    dealCurrency: 'INR',
    dealValue: 180000,
    tags: ['Hot Lead'],
    notes: [],
    followUps: [],
    attachments: [],
    timeline: [
      { id: 'tl-14', type: 'lead_created', title: 'Lead Created', createdAt: daysAgo(30) },
      { id: 'tl-15', type: 'status_changed', title: 'Status Changed to Won', createdAt: daysAgo(2) },
    ],
    createdAt: daysAgo(30),
    updatedAt: daysAgo(2),
  },
];
